package ehe.gordon.model;

import java.util.ArrayList;
import java.util.List;

/**
 * @author lindon-fox
 * 
 */
public class SnippetDefinition {

	private static final String PARAMETER_END_REGEX_SAFE = "\\}\\}\\}";
	private static final String PARAMETER_START_REGEX_SAFE = "\\{\\{\\{";
	private static final String PARAMETER_END = "}}}";
	private static final String PARAMETER_START = "{{{";
	private String name;
	/**
	 * The raw contents contain contents and any number of snippet placeholders
	 * to be substituted.
	 */
	private String rawContents;
	private List<Placeholder> placeholders;

	public SnippetDefinition(String name, String rawContents) {
		super();
		this.name = name;
		setRawContents(rawContents);
//		placeholders = new ArrayList<Placeholder>();
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRawContents() {
		return rawContents;
	}
	

	protected String getParameterSafeRawContents() {
		String parameterSafeContents = rawContents;
		for (Placeholder placeholder : placeholders) {
			//this has some serious problems...
			//try just replacing the actual value (generated by placeholder.toString() - though get it from a different method...)
			String lookingToReplace = getPlaceholderAsParameterWithValuesRegexSafe(placeholder);
			String withThis = getPlaceholderAsParameterRegexSafe(placeholder);
			parameterSafeContents = parameterSafeContents.replaceAll(lookingToReplace, withThis);
		}
		return parameterSafeContents;
	}

	public void setRawContents(String contents) {
		this.rawContents = contents;
		recalculatePlaceholders();
	}

	private void recalculatePlaceholders() {
		placeholders = new ArrayList<Placeholder>();
//		why is this not working?
		assert placeholdersAreValid();
		List<Integer> startIndexes = createIndexListOfOccurances(PARAMETER_START, false);
		List<Integer> endIndexes = createIndexListOfOccurances(PARAMETER_END, true);
		for (int i = 0; i < startIndexes.size(); i++) {
			String placeholderRawContents = getRawContents().substring(startIndexes.get(i), endIndexes.get(i)); 
			placeholders.add(Placeholder.parseRawContents(placeholderRawContents));
		}
	}

	/**
	 * Returns false if there is not enough of these; <code>PARAMETER_START</code>, to to match these
	 * <code>PARAMETER_END</code>
	 * 
	 * @return
	 */
	private boolean placeholdersAreValid() {
		int startCount = countOccurances(PARAMETER_START);
		int endCount = countOccurances(PARAMETER_END);
		return startCount == endCount;
	}

	private int countOccurances(String findStr) {
		int count = 0;
		int lastIndex = 0;
		while (lastIndex != -1) {
			lastIndex = getRawContents().indexOf(findStr, lastIndex);
			if (lastIndex != -1) {
				count++;
				lastIndex += findStr.length();
			}
		}
		return count;
	}

	private List<Integer> createIndexListOfOccurances(String findString, boolean getStart) {
		List<Integer> occurances = new ArrayList<Integer>();
		int lastIndex = 0;
		while (lastIndex != -1) {
			lastIndex = getRawContents().indexOf(findString, lastIndex);
			if (lastIndex != -1) {
				if(getStart){
					occurances.add(lastIndex);	
				}
				else{
					occurances.add(lastIndex + findString.length());	
				}
				lastIndex += findString.length();
				
			}
		}
		return occurances;
	}

	/**
	 * @return the <code>name</code> of the snippet wrapped in the format
	 *         chracters, like this: <code>{{{snippetName}}}</code>.
	 */
	protected String getNameAsParameterRegexSafe() {
		return PARAMETER_START_REGEX_SAFE + this.name + PARAMETER_END_REGEX_SAFE;
	}
	
	protected String getPlaceholderAsParameterRegexSafe(Placeholder placeholder) {
		return PARAMETER_START_REGEX_SAFE + placeholder.getName() + PARAMETER_END_REGEX_SAFE;
	}
	/**
	 * 
	 * @return like <code>getNameAsParameterRegexSafe</code>, but also looking for
	 * values, so will return this: <code>{{{snippetName|*}}}</code>
	 */
	static int count = 0;
	protected String getPlaceholderAsParameterWithValuesRegexSafe(Placeholder placholder){
		System.out.println("" + count);
		String replaceThis = "\\\\";
		String withThis = "\\\\\\\\";
		String defaultValue =placholder.getDefaultValue().replaceAll(replaceThis, withThis);
		return PARAMETER_START_REGEX_SAFE + placholder.getName() + "\\|" + defaultValue + "`" + placholder.getPlaceholderType() + PARAMETER_END_REGEX_SAFE;
	}

	public List<Placeholder> getPlaceHolders() {
		return placeholders;
	}

	@Override
	public String toString() {
		return this.getName() + '\n' + this.getRawContents();
	}
}
