<br/>
<br/>
<table class="bingo_header_table">
<tr>
<td class="bingo_header_date_cell">Date Åy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Åz</td>
<td class="bingo_header_name_cell">Name Åy&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Åz</td>
</tr>
</table>
<h1 class="bingo_heading">Let's enjoy Bingo!</h1>
<h3>[ 1st grade, Katakana English ]</h3>
<table class="bingo_word_title">
<!--word box to select words from-->
{{{generic_tr}}}
</table>
<br/>
<table class="bingo_table">
<tr class="bingo_row">
<th>B</th>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="bingo_row">
<th>I</th>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="bingo_row">
<th>N</th>
<td></td>
<td></td>
<td class="bingo_cell_free">Free!</td>
<td></td>
<td></td>
</tr>
<tr class="bingo_row">
<th>G</th>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="bingo_row">
<th>O</th>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</table>
<!--<a class="image"><img src="file:\\C:\Documents and Settings\TC05\ÉfÉXÉNÉgÉbÉv\Johnny\english pictures\icons\naruto.jpg" /></a><i>Naruto says "I will never give up!"</i>-->