<br/>
<br/>
<table class="bingo_header_table">
<tr>
<td class="bingo_header_date_cell">Date 【&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;】</td>
<td class="bingo_header_name_cell">Name 【&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;】</td>
</tr>
</table>
<h1 class="bingo_heading">Let's enjoy Bingo!</h1>
<div style="float:right;">
	"I want to find Kenpachi. He is amazing, wonderful and fantastic."<a class="image" ><img style="height:80px;" src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\english pictures\for bingo\Yachiru.jpg"/></a>
</div><h3>[ {{{bingo_title|Year X, Unit Y`Value}}} ]</h3>
<table class="bingo_word_title">
<!--word box to select words from-->
{{{generic_tr|`DataList}}}
</table>
<br/>
<table class="bingo_table">
<tr class="bingo_row">
<th>B</th>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
</tr>
<tr class="bingo_row">
<th>I</th>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
</tr>
<tr class="bingo_row">
<th>N</th>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td class="bingo_cell_free">Free!</td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
</tr>
<tr class="bingo_row">
<th>G</th>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
</tr>
<tr class="bingo_row">
<th>O</th>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
<td><a class="image"><img src="file:\\C:\Documents and Settings\TC05\デスクトップ\Johnny\Bingo\ruled lines - new Horizon Style - 50px.gif"/></a></td>
</tr>
</table>
